---
title: "Advanced Bioinformatics 2019 assessment"
author: 'Abubakar:'
date: "5/10/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task 3.1

```{r, echo=FALSE}
sum(5:55)
```


# Task 3.2

```{r, echo=FALSE}
sumfun <- function(n) {sum(5:n)}
sumfun(10)

sumfun(20)

sumfun(100)
```

# Task 3.3

```{r, echo=FALSE}
series <- function(n) {  #function for calculating fibonnaci of a vector with n values
  series <-numeric(n)
  series[1] <- 1 #second element of fibonnaci series is 1
  series[2] <- 1 #second element of fibonnaci series is  2
  i = 3 # start the loop at the third element
  
  while (i <= n) { # repeat the loop upto 12th  element of fib
    series[i]=series[i - 1] + series[i - 2]
    i<- i + 1
  }
  return(series) # return the answer
}

series(12)
```

# Task 3.4

```{r,echo=FALSE}
data(mtcars)


head(mtcars) #view first six rows of mtcars dataset

names(mtcars) #display column names

library(ggplot2)
plot<-ggplot(data=mtcars, aes(x=as.factor(gear),y=mpg)) + geom_boxplot(aes(fill=as.factor(gear))) + labs(title = "miles per gallon as a function of number of gears", y = "Miles per gallon (mpg)", x = "Number of gears (gear)")
plot

```

# Task 3.5

```{r, echo=FALSE}

#The dataset in question was firstly viewed with the following commands
data=cars
y <- cars$dist*0.000189394; x <- cars$speed; #Stopping distance (dist) were converted from ft to miles in order to match units with speed, which is in miles per hour. Assuming that 1 foot equals to 0.000189394 miles, the conversion was achieved by multiplying cars$dist by 0.000189394.
model <- lm(formula = "y~x") #fitting mode
summary(model)

```
# Task 3.6

```{r, echo=FALSE}
#Assign the ggplot function to the variable ggplot_01
newplot <- ggplot(data = cars, aes(x= speed, y=dist)) + geom_point() + geom_smooth(method = "lm",formula = "y ~ x")
# Create a new variable called ggplplot_1.1 and add to it a title, x,y labels.
finalplot <- newplot + ggtitle ("Linear model of the relationship between breaking distance(dist) and speed")+ xlab("speed(milesperhour)")+ ylab("dist(feet)")
finalplot

```

# Task 3.7

```{r, echo=FALSE}
dist_miles <- cars$dist*0.000189394 #distance in miles

break_dist <- cars$speed^2 #the breaking distance variable is set to the square value of the speed
#A linear model is then fitted between the stopping distance in miles (dist_miles) and breaking distance (break_dist)  as a derivative of square rooting the speed in miles per hour.
y <- dist_miles; x <- break_dist;
model <- lm(formula = "y~x")

summary(model) #view summary

#From the model,slope is equal to half the average reaction time, if speed and distance are constant
reaction_time <- 2.443e-05*3600 # Reaction time is therefore equal to two times the value of the slope reaction_time
reaction_time
#Converting reaction time in hours to seconds
coverted_reaction_time <- reaction_time/3600
coverted_reaction_time
#I didn't get resonable results becuase I get a negative value for reaction time
# Plotting 
ggplot(cars,aes(break_dist,dist_miles)) + geom_point() + geom_smooth(method="lm",formula="y~x") + labs (title = "Linear regression of breaking distance and stopping distance", x = "Breaking Distance (miles/h)", y = "Distance (miles)")

```
